In [ ]:
!pip install geopandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 4.1 MB/s
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.3.5)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.4)
Collecting pyproj>=2.2.0
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 59.1 MB/s
Collecting fiona>=1.8
  Downloading Fiona-1.8.21-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)
     |████████████████████████████████| 16.7 MB 39.7 MB/s
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (22.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2022.6.15)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2.8.2)
Installing collected packages: munch, cligj, click-plugins, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.21 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1

In [ ]:
import requests; from urllib.parse import urlparse
import pandas as pd
import geopandas

In [ ]:
# 주소 목록 xlsx 파일 읽기
df = pd.read_csv('/content/drive/Shareddrives/전기차/용인시_단지기본정보/20220901_용인시_단지_기본정보 - 20220901_용인시_단지_기본정보.csv', encoding='UTF-8')

df

,시도,시군구,동리,단지코드,단지명,단지분류,법정동주소,도로명주소,동수,세대수,총주차대수,지상주차대수,지하주차대수
0,용인시,처인구,역북동,A10025716,역북신원아침도시아파트,아파트,경기도 용인처인구 역북동 795 역북신원아침도시아파트,경기도 용인시 처인구 낙은로 11,5,452,490,0,490
1,용인시,처인구,남곡리,A10025679,양지포레스토리,연립주택,경기도 용인처인구 양지면 남곡리 898 양지포레스토리,경기도 용인시 처인구 은이로 85,15,174,185,185,0
2,용인시,처인구,고림동,A10025660,양우내안애에듀퍼스트,아파트,경기도 용인처인구 고림동 1014 양우내안애에듀퍼스트,경기도 용인시 처인구 경안천로 196-1,18,1098,1217,8,1209
3,용인시,기흥구,영덕동,A10025178,힉스유타워 아파트,아파트,경기도 용인기흥구 영덕동 1315 힉스유타워 아파트,경기도 용인시 기흥구 중부대로 184,1,230,265,0,265
4,용인시,수지구,성복동,A10025592,성복역 KCC스위첸,아파트,경기도 용인수지구 성복동 167 성복역 KCC스위첸,경기도 용인시 수지구 성복1로 62,2,188,212,18,194
...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,용인시,수지구,죽전동,A44816003,죽전7차현대홈타운1단지,아파트,경기도 용인수지구 죽전동 1151 죽전7차현대홈타운1단지,경기도 용인시 수지구 탄천상로 7,5,162,178,61,117
464,용인시,기흥구,신갈동,A44658414,기흥더샵프라임뷰,아파트,경기도 용인기흥구 신갈동 733 기흥더샵프라임뷰,경기도 용인시 기흥구 구갈로 71-18,8,612,775,0,775
465,용인시,기흥구,신갈동,A44658415,기흥역롯데캐슬스카이,주상복합,경기도 용인기흥구 신갈동 63 기흥역롯데캐슬스카이,경기도 용인시 기흥구 중부대로 375,3,625,797,0,797
466,용인시,기흥구,서천동,A10027304,힐스테이트 서천 아파트,아파트,경기도 용인기흥구 서천동 801 힐스테이트 서천 아파트,경기도 용인시 기흥구 서천동로 22,12,754,912,4,908
467,용인시,처인구,역북동,A10027347,역북2단지 우남퍼스트빌아파트,아파트,경기도 용인처인구 역북동 282 역북2단지 우남퍼스트빌아파트,경기도 용인시 처인구 낙은로 59,7,505,532,73,459

In [ ]:
# import requests

# url = "https://dapi.kakao.com/v2/local/search/address.json"

# REST_API_KEY = "45820cb466de30218db7ceddac906ac5"#카카오에서 발급받은 api키(요곤 공주꺼)
# headers = {"Authorization": "KakaoAK {}".format(REST_API_KEY)}
# address = "경기도 용인시 처인구 낙은로 59"


# def location_data(address):
#     params = {"query": "{}".format(address)}
#     resp = requests.get(url, params=params, headers=headers)
#     data = resp.json()['documents']
    
#     print(data)

# location_data(address)

[{'address': {'address_name': '경기 용인시 처인구 역북동 787', 'b_code': '4146110200', 'h_code': '4146152500', 'main_address_no': '787', 'mountain_yn': 'N', 'region_1depth_name': '경기', 'region_2depth_name': '용인시 처인구', 'region_3depth_h_name': '역북동', 'region_3depth_name': '역북동', 'sub_address_no': '', 'x': '127.196679365345', 'y': '37.2415236089635'}, 'address_name': '경기 용인시 처인구 낙은로 59', 'address_type': 'ROAD_ADDR', 'road_address': {'address_name': '경기 용인시 처인구 낙은로 59', 'building_name': '역북2단지 우남퍼스트빌', 'main_building_no': '59', 'region_1depth_name': '경기', 'region_2depth_name': '용인시 처인구', 'region_3depth_name': '역북동', 'road_name': '낙은로', 'sub_building_no': '', 'underground_yn': 'N', 'x': '127.196679365345', 'y': '37.2415236089635', 'zone_no': '17045'}, 'x': '127.196679365345', 'y': '37.2415236089635'}]

In [ ]:
# 주소 검색 함수 정의
def address_to_latlon(address):
    url = "https://dapi.kakao.com/v2/local/search/address.json?&query=" + address
    result = requests.get(urlparse(url).geturl(),
                          headers={"Authorization":"KakaoAK 45820cb466de30218db7ceddac906ac5"})#카카오에서 발급받은 api키(요곤 공주꺼)
    json_obj = result.json()
    for document in json_obj['documents']:
        val = [document['address_name'], document['y'], document['x']]
    return val
address_to_latlon(address)

['경기 용인시 처인구 한터로152번길 45', '37.2466295058458', '127.230800386786']

In [ ]:
# 주소 검색 함수 반복 적용
list = []
n=0
for address in df['도로명주소']:
  list.append(address_to_latlon(address))
  n=n+1
  print(n)
    
df1 = pd.DataFrame(list, columns = ['address_name', 'lat', 'lon'])
df1.head()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468

            address_name               lat               lon
0      경기 용인시 처인구 낙은로 11  37.2385704552006  127.197317788422
1  경기 용인시 처인구 양지면 은이로 85  37.2237979176946  127.278730828863
2  경기 용인시 처인구 경안천로 196-1  37.2491879717277  127.221192942292
3    경기 용인시 기흥구 중부대로 184  37.2691613298833  127.090689370086
4     경기 용인시 수지구 성복1로 62  37.3152131053821  127.072942564189

In [ ]:
list

[['경기 용인시 처인구 낙은로 11', '37.2385704552006', '127.197317788422'],
 ['경기 용인시 처인구 양지면 은이로 85', '37.2237979176946', '127.278730828863'],
 ['경기 용인시 처인구 경안천로 196-1', '37.2491879717277', '127.221192942292'],
 ['경기 용인시 기흥구 중부대로 184', '37.2691613298833', '127.090689370086'],
 ['경기 용인시 수지구 성복1로 62', '37.3152131053821', '127.072942564189'],
 ['경기 용인시 기흥구 신정로 25', '37.2730954778418', '127.101431429455'],
 ['경기 용인시 수지구 성복2로 10', '37.3112648289337', '127.083106430916'],
 ['경기 용인시 수지구 풍덕천로171번길 9', '37.3268290106252', '127.099244427714'],
 ['경기 용인시 기흥구 덕영대로2077번길 33', '37.2664821050674', '127.095698664994'],
 ['경기 용인시 기흥구 사은로84번길 10', '37.2540844951938', '127.113437206674'],
 ['경기 용인시 수지구 고기로45번길 40-18', '37.341437124213', '127.094892462148'],
 ['경기 용인시 처인구 금령로12번길 12', '37.2339512861635', '127.198212347459'],
 ['경기 용인시 처인구 포곡읍 포곡로61번길 17', '37.270823929875', '127.212646166538'],
 ['경기 용인시 처인구 포곡읍 포곡로 90', '37.2674506609158', '127.215710104946'],
 ['경기 용인시 처인구 포곡읍 포곡로 98-1', '37.2671835381001', '127.218051635498'],
 ['경기 용인시 처인구 모현읍 백옥대로2332번길 21-8', '37.3324937606486', '127.250215216931'],
 ['경기 용인시 처인구 지삼로590번길 9', '37.2404522884646', '127.167354380587'],
 ['경기 용인시 처인구 포곡읍 포곡로 159', '37.2739215707702', '127.220790267532'],
 ['경기 용인시 처인구 지삼로590번길 24', '37.2385011475596', '127.164732663858'],
 ['경기 용인시 처인구 지삼로590번길 29', '37.23981823994', '127.169118531027'],
 ['경기 용인시 처인구 중부대로1388번길 6-4', '37.2331357792242', '127.197871580251'],
 ['경기 용인시 처인구 중부대로1388번길 6-14', '37.2336070084302', '127.196040016323'],
 ['경기 용인시 처인구 중부대로1388번길 12', '37.2326153723789', '127.197687551642'],
 ['경기 용인시 처인구 중부대로1158번길 12', '37.2376115088833', '127.170550930152'],
 ['경기 용인시 처인구 이동읍 백옥대로587번길 7', '37.1893503511482', '127.204895419447'],
 ['경기 용인시 처인구 모현읍 외대로54번길 12', '37.3343467144271', '127.254026796604'],
 ['경기 용인시 처인구 이동읍 백옥대로621번길 11', '37.1921141579213', '127.204993440662'],
 ['경기 용인시 처인구 이동읍 경기동로705번길 28', '37.1391735837303', '127.201179688583'],
 ['경기 용인시 처인구 금학로1번길 9', '37.2452786266036', '127.167046540248'],
 ['경기 용인시 처인구 경안천로256번길 47-14', '37.2526122273862', '127.227551825988'],
 ['경기 용인시 처인구 경안천로256번길 47-16', '37.2534781668999', '127.226827499995'],
 ['경기 용인시 처인구 남사읍 한숲로 83', '37.1581701311615', '127.170126776434'],
 ['경기 용인시 처인구 남사읍 한숲로 84', '37.1561090694356', '127.173656345397'],
 ['경기 용인시 처인구 남사읍 한숲로 123', '37.1601463360453', '127.172057132033'],
 ['경기 용인시 처인구 남사읍 한숲로 124', '37.1591118282048', '127.175501302175'],
 ['경기 용인시 처인구 남사읍 한숲로 137', '37.161355406237', '127.173948565082'],
 ['경기 용인시 처인구 한터로152번길 45', '37.2466295058458', '127.230800386786'],
 ['경기 용인시 처인구 한터로152번길 62', '37.2445675069567', '127.23220969308'],
 ['경기 용인시 처인구 한터로275번길 40', '37.2578531115269', '127.237250220806'],
 ['경기 용인시 처인구 영문로29번길 17', '37.2669935846693', '127.207068856228'],
 ['경기 용인시 처인구 모현읍 문현로 326', '37.3366524310217', '127.243929947043'],
 ['경기 용인시 처인구 금령로173번길 5', '37.2351635559951', '127.215343222091'],
 ['경기 용인시 처인구 금령로173번길 14', '37.2354292806482', '127.216919538729'],
 ['경기 용인시 처인구 명지로16번길 25', '37.2332338175126', '127.185165049744'],
 ['경기 용인시 처인구 명지로16번길 26', '37.2356068835221', '127.185291322676'],
 ['경기 용인시 처인구 이동읍 이원로 22', '37.1893860997942', '127.209494314665'],
 ['경기 용인시 처인구 포곡읍 백옥대로1898번길 34', '37.2945130429444', '127.238272172635'],
 ['경기 용인시 처인구 금령로106번길 14-8', '37.2345837683508', '127.207243318428'],
 ['경기 용인시 처인구 금령로13번길 13', '37.2366019643714', '127.197790934347'],
 ['경기 용인시 처인구 백옥대로1068번길 12', '37.2292990888889', '127.211752887497'],
 ['경기 용인시 처인구 한터로152번길 15', '37.2471012084189', '127.229916936429'],
 ['경기 용인시 처인구 명지로40번길 35-16', '37.2306890205109', '127.182243414418'],
 ['경기 용인시 처인구 명지로40번길 35-29', '37.2308219194505', '127.184400660885'],
 ['경기 용인시 기흥구 동백죽전대로 507', '37.2830246609485', '127.150608535392'],
 ['경기 용인시 기흥구 중부대로 376', '37.2714574421973', '127.108875146108'],
 ['경기 용인시 수지구 만현로67번길 20', '37.3082964964469', '127.088522841076'],
 ['경기 용인시 기흥구 기흥로 29', '37.2791830690322', '127.114302620407'],
 ['경기 용인시 수지구 포은대로313번길 7-10', '37.3166948096886', '127.083890038258'],
 ['경기 용인시 기흥구 기흥역로58번길 10', '37.2739931969359', '127.119029735417'],
 ['경기 용인시 기흥구 기흥역로58번길 56', '37.2718101606869', '127.120450974178'],
 ['경기 용인시 기흥구 기흥역로58번길 78', '37.2734741309411', '127.118016537449'],
 ['경기 용인시 수지구 정평로 73', '37.3225443124245', '127.089196068087'],
 ['경기 용인시 수지구 정평로 89', '37.3234189743597', '127.089396011329'],
 ['경기 용인시 수지구 정평로 116', '37.3236363477992', '127.093535019528'],
 ['경기 용인시 수지구 용구대로 2720', '37.3289448201755', '127.109356906504'],
 ['경기 용인시 수지구 용구대로 2742', '37.3299184981879', '127.110109228916'],
 ['경기 용인시 기흥구 용구대로2394번길 27', '37.300391782518', '127.113463292513'],
 ['경기 용인시 수지구 상현로11번길 26', '37.3042019528875', '127.07811049245'],
 ['경기 용인시 수지구 상현로42번길 40', '37.3027374662266', '127.082410810687'],
 ['경기 용인시 수지구 상현로42번길 46', '37.3043997658393', '127.081922638701'],
 ['경기 용인시 기흥구 용구대로2469번길 20', '37.3084578364206', '127.106199114923'],
 ['경기 용인시 수지구 포은대로 231', '37.3092751497397', '127.080916308005'],
 ['경기 용인시 수지구 포은대로 298', '37.3134183637284', '127.086908225259'],
 ['경기 용인시 수지구 탄천상로 6', '37.3323916559125', '127.112212186294'],
 ['경기 용인시 수지구 탄천상로 29', '37.3342417333537', '127.110980687671'],
 ['경기 용인시 수지구 탄천상로 30', '37.3343901562391', '127.112388031093'],
 ['경기 용인시 수지구 고기로 3', '37.3423585091681', '127.10120807185'],
 ['경기 용인시 수지구 고기로 11', '37.3425455170361', '127.099990525707'],
 ['경기 용인시 수지구 고기로 89', '37.3447488936611', '127.091532269053'],
 ['경기 용인시 수지구 진산로 24', '37.3141394988568', '127.092792577773'],
 ['경기 용인시 수지구 태봉로 17', '37.3346648490018', '127.057444452313'],
 ['경기 용인시 수지구 풍덕천로 19', '37.3193195915051', '127.085303522814'],
 ['경기 용인시 수지구 풍덕천로 33', '37.3189183191966', '127.086478742702'],
 ['경기 용인시 수지구 풍덕천로 52', '37.3175763161289', '127.090813615263'],
 ['경기 용인시 수지구 풍덕천로 75', '37.3205039309399', '127.09049097484'],
 ['경기 용인시 수지구 풍덕천로 76', '37.3199747278095', '127.09087798744'],
 ['경기 용인시 기흥구 동백1로 9', '37.2647476191309', '127.15759236242'],
 ['경기 용인시 기흥구 동백1로 12', '37.2633050050851', '127.158908351542'],
 ['경기 용인시 수지구 풍덕천로 91', '37.3210632746953', '127.091568069816'],
 ['경기 용인시 기흥구 신갈로138번길 12', '37.2786181570696', '127.107329969039'],
 ['경기 용인시 수지구 정평로13번길 20', '37.3172407435084', '127.087013031429'],
 ['경기 용인시 기흥구 죽현로 12', '37.3193086078075', '127.111225429388'],
 ['경기 용인시 기흥구 동백2로 11', '37.2689745618693', '127.155014055896'],
 ['경기 용인시 기흥구 동백2로 12', '37.2662456777001', '127.156651069468'],
 ['경기 용인시 기흥구 동백2로 37', '37.2697295041552', '127.15709471939'],
 ['경기 용인시 기흥구 한보라1로43번길 22', '37.2491293427057', '127.110722511198'],
 ['경기 용인시 기흥구 한보라1로43번길 23', '37.2502657928233', '127.110761595554'],
 ['경기 용인시 기흥구 한보라1로64번길 22', '37.2523193909809', '127.106806385425'],
 ['경기 용인시 기흥구 용구대로 2242', '37.2866334673516', '127.108090705262'],
 ['경기 용인시 기흥구 연원로 60', '37.3027099080142', '127.112107839272'],
 ['경기 용인시 기흥구 연원로 49', '37.3032620270871', '127.110613570424'],
 ['경기 용인시 기흥구 예현로 15', '37.2444058449991', '127.073035775145'],
 ['경기 용인시 수지구 정평로 41', '37.3197733757524', '127.085893402078'],
 ['경기 용인시 수지구 정평로 61', '37.3218783140646', '127.086341106584'],
 ['경기 용인시 기흥구 죽전로 20', '37.3199965224732', '127.110385262396'],
 ['경기 용인시 기흥구 고매로34번길 10', '37.2299223038764', '127.112152113636'],
 ['경기 용인시 기흥구 고매로34번길 31', '37.228669875383', '127.115036410943'],
 ['경기 용인시 수지구 풍덕천로 161', '37.3262889185527', '127.098505591896'],
 ['경기 용인시 수지구 포은대로 467', '37.3236036964448', '127.100817588259'],
 ['경기 용인시 수지구 포은대로 477', '37.3240902915367', '127.101826107888'],
 ['경기 용인시 수지구 포은대로 219', '37.3079232977462', '127.080031399666'],
 ['경기 용인시 기흥구 용구대로2518번길 15', '37.3129971148668', '127.109314850062'],
 ['경기 용인시 기흥구 고매로43번길 32-2', '37.232501816743', '127.11754493797'],
 ['경기 용인시 수지구 수지로342번길 18', '37.326643947419', '127.09359437228'],
 ['경기 용인시 수지구 수지로78번길 20', '37.3099961684187', '127.079168951147'],
 ['경기 용인시 기흥구 중부대로 820', '37.2560378542011', '127.142764338538'],
 ['경기 용인시 기흥구 동백죽전대로 455-10', '37.2797770784079', '127.151431633723'],
 ['경기 용인시 기흥구 동백죽전대로 455-17', '37.279797933497', '127.148411081312'],
 ['경기 용인시 기흥구 보정로 26', '37.3134429658859', '127.110651385835'],
 ['경기 용인시 기흥구 보정로 30', '37.31037251816', '127.112270035886'],
 ['경기 용인시 수지구 신봉1로48번길 29', '37.3242608508507', '127.080819660427'],
 ['경기 용인시 수지구 신봉1로48번길 32', '37.3234819167496', '127.081855570927'],
 ['경기 용인시 수지구 신봉1로48번길 45', '37.3243410133616', '127.083073893376'],
 ['경기 용인시 수지구 신봉1로71번길 25', '37.3209209251706', '127.077827688844'],
 ['경기 용인시 기흥구 사은로126번길 10', '37.2516865812303', '127.117560419708'],
 ['경기 용인시 수지구 성복2로 220', '37.3206362895327', '127.062646296865'],
 ['경기 용인시 수지구 성복2로 251', '37.3188611757842', '127.061245659132'],
 ['경기 용인시 기흥구 구성로 90', '37.293235775676', '127.119390375907'],
 ['경기 용인시 수지구 대지로 49', '37.3298362838424', '127.114051642154'],
 ['경기 용인시 수지구 푸른솔로 20', '37.3221032474705', '127.116015814547'],
 ['경기 용인시 수지구 푸른솔로 49', '37.3247649963642', '127.1150844626'],
 ['경기 용인시 수지구 푸른솔로 55', '37.3257852846387', '127.116781371385'],
 ['경기 용인시 수지구 푸른솔로 56', '37.3247644499038', '127.116013136068'],
 ['경기 용인시 수지구 푸른솔로 76', '37.3252293328574', '127.118877403'],
 ['경기 용인시 수지구 푸른솔로 88', '37.3259169677641', '127.119892359954'],
 ['경기 용인시 기흥구 덕영대로 1871', '37.2536308000942', '127.089485497263'],
 ['경기 용인시 기흥구 보정로 87', '37.3174411419798', '127.113298031222'],
 ['경기 용인시 기흥구 보정로 88', '37.3175653531454', '127.116037269166'],
 ['경기 용인시 기흥구 사은로 64', '37.2550925152079', '127.112563315604'],
 ['경기 용인시 기흥구 한보라2로 93', '37.2484467878653', '127.111792281652'],
 ['경기 용인시 기흥구 한보라2로 141', '37.2457079413222', '127.110289325998'],
 ['경기 용인시 기흥구 한보라2로 167', '37.2423725664651', '127.10791769234'],
 ['경기 용인시 기흥구 한보라2로 168', '37.2441459576275', '127.108657093653'],
 ['경기 용인시 수지구 만현로 79', '37.3092963306289', '127.087125703137'],
 ['경기 용인시 수지구 만현로 99', '37.3068568752278', '127.088452119999'],
 ['경기 용인시 수지구 만현로 107', '37.3054138643226', '127.089890628688'],
 ['경기 용인시 수지구 만현로 127', '37.3045669037746', '127.087711863009'],
 ['경기 용인시 수지구 문인로 59', '37.3316072715362', '127.096963739196'],
 ['경기 용인시 기흥구 사은로126번길 33', '37.25216946929', '127.121293829145'],
 ['경기 용인시 기흥구 사은로126번길 46', '37.2527177393252', '127.119536406044'],
 ['경기 용인시 기흥구 기흥역로 9', '37.2748218442608', '127.115337289593'],
 ['경기 용인시 기흥구 기흥역로 16', '37.2736113791937', '127.114974755575'],
 ['경기 용인시 기흥구 기흥역로 63', '37.2748427696292', '127.118778508807'],
 ['경기 용인시 수지구 대지로15번길 60', '37.3330204023368', '127.11474161271'],
 ['경기 용인시 기흥구 새천년로16번길 16', '37.2892514676663', '127.109815597556'],
 ['경기 용인시 기흥구 서천동로21번길 5', '37.2391393204793', '127.076329046868'],
 ['경기 용인시 수지구 현암로 3', '37.3325339272573', '127.110200608355'],
 ['경기 용인시 수지구 광교마을로 2', '37.2985835294125', '127.067432179743'],
 ['경기 용인시 수지구 광교마을로 11', '37.298078336053', '127.063489837285'],
 ['경기 용인시 수지구 대지로 64', '37.32828727849', '127.116224131621'],
 ['경기 용인시 수지구 대지로 77', '37.3300300919113', '127.117644579167'],
 ['경기 용인시 수지구 풍덕천로22번길 67', '37.3141215879111', '127.082291135141'],
 ['경기 용인시 수지구 풍덕천로30번길 20', '37.316426291098', '127.087268518805'],
 ['경기 용인시 수지구 상현로 2', '37.3017233813448', '127.073033189992'],
 ['경기 용인시 수지구 상현로 27', '37.3034007906717', '127.076533924181'],
 ['경기 용인시 수지구 상현로 30-6', '37.3018801976153', '127.077234515132'],
 ['경기 용인시 수지구 상현로 30-9', '37.3015146416015', '127.07874712941'],
 ['경기 용인시 수지구 상현로 30-10', '37.3005381667832', '127.077000005339'],
 ['경기 용인시 수지구 상현로 58', '37.3027759618892', '127.080547389653'],
 ['경기 용인시 수지구 상현로 59', '37.3054508703928', '127.079072481359'],
 ['경기 용인시 수지구 상현로 67-12', '37.3055751000214', '127.080576318648'],
 ['경기 용인시 수지구 상현로 88', '37.3032525044105', '127.083431033245'],
 ['경기 용인시 수지구 상현로 100', '37.3045167299046', '127.084472410819'],
 ['경기 용인시 수지구 상현로 101', '37.307620805959', '127.083316064975'],
 ['경기 용인시 수지구 상현로 119-6', '37.3095322121113', '127.083896631359'],
 ['경기 용인시 수지구 동천로63번길 10', '37.3384624431927', '127.097356569169'],
 ['경기 용인시 수지구 동천로135번길 21', '37.3340292884234', '127.087424512062'],
 ['경기 용인시 기흥구 관곡로 16', '37.2811569983481', '127.106551123415'],
 ['경기 용인시 수지구 대지로 127', '37.3306508998433', '127.122530071092'],
 ['경기 용인시 수지구 대지로 139', '37.3308207243492', '127.12572686296'],
 ['경기 용인시 수지구 동천로 18', '37.3416386427247', '127.099976006846'],
 ['경기 용인시 수지구 동천로 53', '37.3400462851402', '127.096904395154'],
 ['경기 용인시 수지구 동천로 64', '37.34097274539', '127.098298727226'],
 ['경기 용인시 수지구 동천로 93', '37.3384365703794', '127.093917526737'],
 ['경기 용인시 기흥구 마북로247번길 3', '37.3092277880156', '127.130507821299'],
 ['경기 용인시 수지구 현암로125번길 11', '37.3336370845464', '127.120082011998'],
 ['경기 용인시 수지구 현암로63번길 2', '37.3320946107826', '127.117023130661'],
 ['경기 용인시 기흥구 언남로 5', '37.2929722800738', '127.123979272219'],
 ['경기 용인시 기흥구 언남로 15', '37.2939727333271', '127.127511504781'],
 ['경기 용인시 수지구 용구대로2771번길 66', '37.3351174990364', '127.105404087376'],
 ['경기 용인시 수지구 용구대로2771번길 68', '37.3364136934898', '127.106842175165'],
 ['경기 용인시 수지구 용구대로2771번길 88', '37.3374920497986', '127.105331686143'],
 ['경기 용인시 기흥구 관곡로 53', '37.2835576353296', '127.11230303614'],
 ['경기 용인시 기흥구 구갈로28번길 21-21', '37.2794617435937', '127.113477309335'],
 ['경기 용인시 기흥구 구갈로28번길 32', '37.2764585775749', '127.115250598054'],
 ['경기 용인시 기흥구 동백중앙로 41', '37.2599992429272', '127.162705131776'],
 ['경기 용인시 기흥구 동백중앙로 73', '37.2625313576857', '127.159855265494'],
 ['경기 용인시 기흥구 동백중앙로 312', '37.2795698792809', '127.158221445654'],
 ['경기 용인시 기흥구 동백평촌로 15', '37.2848275447757', '127.155420952554'],
 ['경기 용인시 기흥구 동백평촌로 39', '37.2817568676234', '127.154961672508'],
 ['경기 용인시 기흥구 동백평촌로 70', '37.2793964829638', '127.155734867915'],
 ['경기 용인시 기흥구 흥덕4로30번길 11', '37.2762630808747', '127.091599921079'],
 ['경기 용인시 기흥구 기흥로38번길 34', '37.2783686804919', '127.118005460906'],
 ['경기 용인시 기흥구 구갈로 115-16', '37.2855318102771', '127.10902679406'],
 ['경기 용인시 기흥구 구갈로 16', '37.2764905526883', '127.112547023281'],
 ['경기 용인시 기흥구 구교동로 17', '37.3067668017301', '127.10676885593'],
 ['경기 용인시 기흥구 이현로30번길 7', '37.3091076737644', '127.098150516867'],
 ['경기 용인시 기흥구 구교동로118번길 7', '37.302936928161', '127.118260176148'],
 ['경기 용인시 기흥구 중부대로55번길 11', '37.2681737532139', '127.076022823788'],
 ['경기 용인시 기흥구 구성로39번길 13', '37.2964400293286', '127.113073665203'],
 ['경기 용인시 기흥구 구성로53번길 20', '37.2967224748154', '127.115990695904'],
 ['경기 용인시 기흥구 진산로 140', '37.3216459905545', '127.101697126542'],
 ['경기 용인시 수지구 고기로45번길 58', '37.3394355971719', '127.092591109409'],
 ['경기 용인시 수지구 문정로 55', '37.3257210533848', '127.092174417062'],
 ['경기 용인시 수지구 심곡로 16', '37.3077681224143', '127.078577793587'],
 ['경기 용인시 기흥구 중부대로 735', '37.2625014944037', '127.141098726133'],
 ['경기 용인시 기흥구 마북로 186', '37.3054590259479', '127.126780680363'],
 ['경기 용인시 기흥구 마북로 210', '37.3070090109714', '127.128263217012'],
 ['경기 용인시 기흥구 신정로41번길 31', '37.2764366237461', '127.100799752645'],
 ['경기 용인시 수지구 성복1로 80', '37.3156726620216', '127.071267962717'],
 ['경기 용인시 수지구 성복1로 91', '37.3147348895475', '127.069715242799'],
 ['경기 용인시 수지구 성복1로 107', '37.3147275407863', '127.065383727095'],
 ['경기 용인시 기흥구 동백8로 89', '37.2853796792812', '127.161230518699'],
 ['경기 용인시 기흥구 동백8로 90', '37.2842166067514', '127.160111317632'],
 ['경기 용인시 기흥구 동백8로 103', '37.2850106257459', '127.163846827571'],
 ['경기 용인시 기흥구 동백8로 126', '37.2822444950203', '127.164066243807'],
 ['경기 용인시 수지구 정든로 22', '37.3276836869479', '127.115846685568'],
 ['경기 용인시 수지구 이현로 125', '37.3128965349075', '127.090448351574'],
 ['경기 용인시 수지구 죽전로 87', '37.3226931003233', '127.118073716176'],
 ['경기 용인시 수지구 죽전로 111', '37.3237783132207', '127.119232659534'],
 ['경기 용인시 수지구 죽전로 116', '37.3229002059675', '127.121847765065'],
 ['경기 용인시 수지구 죽전로 121', '37.3236619856559', '127.12030510085'],
 ['경기 용인시 수지구 디지털벨리로 5', '37.3280362615077', '127.131856973928'],
 ['경기 용인시 기흥구 금화로11번길 9', '37.262168898647', '127.105366375032'],
 ['경기 용인시 기흥구 금화로11번길 10', '37.2624627769001', '127.107219332889'],
 ['경기 용인시 수지구 성복1로 157', '37.3159379794128', '127.06274043236'],
 ['경기 용인시 수지구 성복1로 222', '37.3221480267536', '127.061648169477'],
 ['경기 용인시 수지구 성복2로 86', '37.31695333469', '127.07528876261'],
 ['경기 용인시 기흥구 동백8로131번길 9', '37.2828580305422', '127.164442515197'],
 ['경기 용인시 기흥구 동백8로131번길 20', '37.2833618682198', '127.16652141053'],
 ['경기 용인시 수지구 성복1로163번길 11', '37.3159552995459', '127.060977964558'],
 ['경기 용인시 수지구 성복1로164번길 13', '37.3183227202926', '127.064298835594'],
 ['경기 용인시 수지구 성복1로164번길 20', '37.3176034747725', '127.064868055335'],
 ['경기 용인시 수지구 죽전로 143', '37.3248994660764', '127.12396897438'],
 ['경기 용인시 수지구 죽전로 244', '37.3324293267349', '127.130723409382'],
 ['경기 용인시 수지구 죽전로 267', '37.334953392727', '127.126066294742'],
 ['경기 용인시 수지구 대지로 19', '37.327872639172', '127.111813264774'],
 ['경기 용인시 수지구 대지로 27', '37.3281317963022', '127.113118995999'],
 ['경기 용인시 기흥구 동백죽전대로 283', '37.2633044322536', '127.153954452763'],
 ['경기 용인시 수지구 디지털벨리로 21', '37.329872375806', '127.132348302732'],
 ['경기 용인시 기흥구 서그내로16번길 14', '37.2456694256064', '127.072374832462'],
 ['경기 용인시 기흥구 서그내로16번길 30', '37.2454907178065', '127.070332164053'],
 ['경기 용인시 수지구 현암로 54', '37.3312019365771', '127.114653204506'],
 ['경기 용인시 수지구 광교마을로 62', '37.2980951617498', '127.071136107425'],
 ['경기 용인시 수지구 광교마을로 90', '37.2952051161118', '127.075593136434'],
 ['경기 용인시 기흥구 동탄기흥로 864', '37.235891750118', '127.102908340046'],
 ['경기 용인시 수지구 신봉3로11번길 10-7', '37.3260921140314', '127.067594630185'],
 ['경기 용인시 수지구 신봉3로12번길 9', '37.3302199204965', '127.064862201305'],
 ['경기 용인시 수지구 신수로683번길 19', '37.329987610414', '127.099313461978'],
 ['경기 용인시 수지구 신수로783번길 50', '37.3425443581459', '127.098795974794'],
 ['경기 용인시 기흥구 공세로 226', '37.2400290211559', '127.102562903765'],
 ['경기 용인시 기흥구 공세로 76', '37.2314220538897', '127.109696063763'],
 ['경기 용인시 기흥구 마북로154번길 16', '37.3024827565463', '127.125738100181'],
 ['경기 용인시 수지구 수풍로23번길 25', '37.3270146379688', '127.086358717652'],
 ['경기 용인시 수지구 신봉1로172번길 8', '37.3287865414389', '127.069648225532'],
 ['경기 용인시 기흥구 서그내로 31', '37.2451107968065', '127.075235718937'],
 ['경기 용인시 수지구 만현로 25', '37.3112178333858', '127.090073064781'],
 ['경기 용인시 기흥구 중부대로746번길 20', '37.2606192382548', '127.136781689486'],
 ['경기 용인시 기흥구 중부대로746번길 21', '37.2604849291054', '127.138070181087'],
 ['경기 용인시 기흥구 금화로58번길 10', '37.2621614363767', '127.109518545757'],
 ['경기 용인시 기흥구 금화로82번길 14', '37.2647013177693', '127.110847444307'],
 ['경기 용인시 기흥구 금화로82번길 17', '37.2661944455713', '127.111793032675'],
 ['경기 용인시 기흥구 덕영대로2077번길 8', '37.2690334569471', '127.095855224609'],
 ['경기 용인시 기흥구 덕영대로2077번길 20', '37.2675557588544', '127.096287742686'],
 ['경기 용인시 기흥구 덕영대로2077번길 53', '37.2651606454878', '127.093546638446'],
 ['경기 용인시 기흥구 덕영대로2077번길 55', '37.2653390169452', '127.092212720784'],
 ['경기 용인시 기흥구 탑실로 15', '37.2390627712733', '127.107802867191'],
 ['경기 용인시 기흥구 탑실로 152', '37.2438517617465', '127.120931223097'],
 ['경기 용인시 기흥구 서천동로 60', '37.2355510623789', '127.075095831711'],
 ['경기 용인시 수지구 상현로 142', '37.3107490147914', '127.085095301061'],
 ['경기 용인시 기흥구 동백4로 26', '37.2715113932588', '127.155462690092'],
 ['경기 용인시 기흥구 동백4로 72', '37.2708819348205', '127.157433773015'],
 ['경기 용인시 기흥구 동백5로 41', '37.2759193992434', '127.154890510455'],
 ['경기 용인시 기흥구 동백5로 79', '37.277304266373', '127.157372954143'],
 ['경기 용인시 수지구 광교호수로 431', '37.3026023385572', '127.08416392288'],
 ['경기 용인시 기흥구 신구로42번길 15', '37.2763076829334', '127.111264173511'],
 ['경기 용인시 기흥구 신구로42번길 22', '37.275674254595', '127.111739623189'],
 ['경기 용인시 수지구 죽전로27번길 14-30', '37.3212463544349', '127.113706289114'],
 ['경기 용인시 수지구 죽전로27번길 60', '37.325852256569', '127.112287195228'],
 ['경기 용인시 기흥구 고매로 16', '37.2312068798664', '127.110957845049'],
 ['경기 용인시 기흥구 고매로 26', '37.2311643641017', '127.11218674511'],
 ['경기 용인시 수지구 성복2로76번길 31', '37.315676733321', '127.079716297203'],
 ['경기 용인시 수지구 성복1로281번길 20', '37.3252174638868', '127.052135737832'],
 ['경기 용인시 기흥구 동백7로 56', '37.2817373119883', '127.157828383583'],
 ['경기 용인시 기흥구 흥덕1로79번길 9', '37.2755121533177', '127.070852363355'],
 ['경기 용인시 기흥구 흥덕1로79번길 37', '37.277975571288', '127.070593415212'],
 ['경기 용인시 기흥구 흥덕2로117번길 14', '37.2790005717998', '127.072420377421'],
 ['경기 용인시 기흥구 흥덕2로118번길 25', '37.2782697708764', '127.077078008295'],
 ['경기 용인시 기흥구 흥덕2로118번길 26', '37.2773277008991', '127.077404490044'],

In [ ]:
dff = pd.DataFrame (list, columns = ['주소','y','x'])
print (dff)
dff.to_csv('/content/drive/Shareddrives/전기차/용인시_단지기본정보/위경도_주거지.csv')

                        주소                 y                 x
0        경기 용인시 처인구 낙은로 11  37.2385704552006  127.197317788422
1    경기 용인시 처인구 양지면 은이로 85  37.2237979176946  127.278730828863
2    경기 용인시 처인구 경안천로 196-1  37.2491879717277  127.221192942292
3      경기 용인시 기흥구 중부대로 184  37.2691613298833  127.090689370086
4       경기 용인시 수지구 성복1로 62  37.3152131053821  127.072942564189
..                     ...               ...               ...
463      경기 용인시 수지구 탄천상로 7  37.3316949444179   127.11158129507
464   경기 용인시 기흥구 구갈로 71-18  37.2826672623871  127.110737118808
465    경기 용인시 기흥구 중부대로 375  37.2719908869697   127.10785938159
466     경기 용인시 기흥구 서천동로 22   37.238322395798  127.075684044275
467      경기 용인시 처인구 낙은로 59  37.2415236089635  127.196679365345

[468 rows x 3 columns]

In [ ]:
df2 = dff[['y','x']]
df2

                    y                 x
0    37.2385704552006  127.197317788422
1    37.2237979176946  127.278730828863
2    37.2491879717277  127.221192942292
3    37.2691613298833  127.090689370086
4    37.3152131053821  127.072942564189
..                ...               ...
463  37.3316949444179   127.11158129507
464  37.2826672623871  127.110737118808
465  37.2719908869697   127.10785938159
466   37.238322395798  127.075684044275
467  37.2415236089635  127.196679365345

[468 rows x 2 columns]

In [ ]:
df_13_axis1 = pd.concat([df, df2], axis=1) 
df_13_axis1

,시도,시군구,동리,단지코드,단지명,단지분류,법정동주소,도로명주소,동수,세대수,총주차대수,지상주차대수,지하주차대수,y,x
0,용인시,처인구,역북동,A10025716,역북신원아침도시아파트,아파트,경기도 용인처인구 역북동 795 역북신원아침도시아파트,경기도 용인시 처인구 낙은로 11,5,452,490,0,490,37.2385704552006,127.197317788422
1,용인시,처인구,남곡리,A10025679,양지포레스토리,연립주택,경기도 용인처인구 양지면 남곡리 898 양지포레스토리,경기도 용인시 처인구 은이로 85,15,174,185,185,0,37.2237979176946,127.278730828863
2,용인시,처인구,고림동,A10025660,양우내안애에듀퍼스트,아파트,경기도 용인처인구 고림동 1014 양우내안애에듀퍼스트,경기도 용인시 처인구 경안천로 196-1,18,1098,1217,8,1209,37.2491879717277,127.221192942292
3,용인시,기흥구,영덕동,A10025178,힉스유타워 아파트,아파트,경기도 용인기흥구 영덕동 1315 힉스유타워 아파트,경기도 용인시 기흥구 중부대로 184,1,230,265,0,265,37.2691613298833,127.090689370086
4,용인시,수지구,성복동,A10025592,성복역 KCC스위첸,아파트,경기도 용인수지구 성복동 167 성복역 KCC스위첸,경기도 용인시 수지구 성복1로 62,2,188,212,18,194,37.3152131053821,127.072942564189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,용인시,수지구,죽전동,A44816003,죽전7차현대홈타운1단지,아파트,경기도 용인수지구 죽전동 1151 죽전7차현대홈타운1단지,경기도 용인시 수지구 탄천상로 7,5,162,178,61,117,37.3316949444179,127.11158129507
464,용인시,기흥구,신갈동,A44658414,기흥더샵프라임뷰,아파트,경기도 용인기흥구 신갈동 733 기흥더샵프라임뷰,경기도 용인시 기흥구 구갈로 71-18,8,612,775,0,775,37.2826672623871,127.110737118808
465,용인시,기흥구,신갈동,A44658415,기흥역롯데캐슬스카이,주상복합,경기도 용인기흥구 신갈동 63 기흥역롯데캐슬스카이,경기도 용인시 기흥구 중부대로 375,3,625,797,0,797,37.2719908869697,127.10785938159
466,용인시,기흥구,서천동,A10027304,힐스테이트 서천 아파트,아파트,경기도 용인기흥구 서천동 801 힐스테이트 서천 아파트,경기도 용인시 기흥구 서천동로 22,12,754,912,4,908,37.238322395798,127.075684044275
467,용인시,처인구,역북동,A10027347,역북2단지 우남퍼스트빌아파트,아파트,경기도 용인처인구 역북동 282 역북2단지 우남퍼스트빌아파트,경기도 용인시 처인구 낙은로 59,7,505,532,73,459,37.2415236089635,127.196679365345

In [ ]:
df_13_axis1.to_csv('/content/drive/Shareddrives/전기차/용인시_단지기본정보/mod주영_용인시_단지_기본정보.csv')